run:
  go: '1.22'
  concurrency: 4
  issues-exit-code: 1
  tests: false
  modules-download-mode: mod
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - execinquery
    - gomnd
    - exhaustruct
    - nonamedreturns
    - wrapcheck
    - gofumpt
    - gci
    - tagliatelle
    - musttag
    - varnamelen
    - testpackage
    - goerr113
    - exhaustivestruct

linters-settings:
  gosec:
    excludes:
      - G401
      - G505
      - G306
  misspell:
    ignore-words:
      - sub_payed
  whitespace:
    multi-if: true
    multi-func: false
  lll:
    line-length: 140
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd
          - filippo.io/edwards25519
          - golang.org/x/crypto
          - gitlab.wildberries.ru/electr/business/orders
          - github.com/jackc/pgx/v5
          - github.com/stretchr/testify
          - github.com/golang/mock/gomock
          - github.com/lib/pq
          - github.com/gofiber/fiber/v2
          - github.com/Masterminds/squirrel
          - golang.org/x/text/encoding/charmap
          - github.com/golang-jwt/jwt/v5
          - github.com/google/uuid
          - github.com/joho/godotenv
          - github.com/caarlos0/env/v6
          - github.com/pressly/goose/v3
          - github.com/shopspring/decimal
          - github.com/gofiber/contrib/jwt
          - github.com/prometheus/client_golang/prometheus/promhttp
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  varnamelen:
    ignore-names:
      - ok
      - bs
      - err
      - rv
      - nm
      - tx
      - id
      - wg
      - i
      - db
      - fn
      - tt
  funlen:
    lines: 100
    ignore-comments: true
    statements: 50

issues:
  exclude-rules:
    - linters:
        - lll
      source: ".*// "